Listener logic errors
quedexnet/java-api pull request #23
Opened 2020-04-09 19:21 UTC by HubertBubert

2020-04-10 09:30 UTC, wgromniak requested changes

2020-04-10 09:30 UTC, wgromniak commented on src/main/java/net/quedex/api/common/ListenerException.java
> +public class ListenerException extends Exception {
Add documentation explaining when this exception is thrown and what it means. Also add relevant documentation in error listener (what exceptions should be expected).

2020-04-10 09:30 UTC, wgromniak commented on src/main/java/net/quedex/api/common/MessageReceiver.java
> +    protected void runListener(final Runnable listenerUpdate) throws ListenerException {
Be consistent with `final`, we don't `final` anywhere in this file.

2020-05-22 06:39 UTC, mchalapuk approved these changes

2020-05-22 08:35 UTC, wgromniak approved these changes

2020-05-28 17:26 UTC, merged